name: iris-env
channels:
  - conda-forge
dependencies:
  - python=3.8.12
  - pip=21.3.1
  - pip:
      - azureml-mlflow==1.41.0
      - azureml-defaults==1.41.0
      - pandas==1.4.1
      - scikit-learn==1.0.2
      - git+https://github.com/microsoft/MLOpsTemplate.git@monitoring-main#subdirectory=src/utilities